/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2024-12-04 07:21:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class instructor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Instructor Dashboard - E-Learning Platform</title>\n");
      out.write("    \n");
      out.write("    <!-- Favicon -->\n");
      out.write("    <link href=\"assets/img/favicon.png\" rel=\"icon\">\n");
      out.write("    \n");
      out.write("    <!-- Google Fonts -->\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    <!-- Vendor CSS Files -->\n");
      out.write("    <link href=\"assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/vendor/aos/aos.css\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --primary: #2b55cc;\n");
      out.write("            --secondary: #1e40af;\n");
      out.write("            --success: #22c55e;\n");
      out.write("            --danger: #ef4444;\n");
      out.write("            --warning: #f59e0b;\n");
      out.write("            --info: #3b82f6;\n");
      out.write("            --light: #f8fafc;\n");
      out.write("            --dark: #1e293b;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: 'Poppins', sans-serif;\n");
      out.write("            background: var(--light);\n");
      out.write("            overflow-x: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Sidebar */\n");
      out.write("        .sidebar {\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            height: 100%;\n");
      out.write("            width: 260px;\n");
      out.write("            background: #fff;\n");
      out.write("            padding: 20px;\n");
      out.write("            transition: all 0.4s ease;\n");
      out.write("            z-index: 1000;\n");
      out.write("            box-shadow: 0 0 20px rgba(0,0,0,0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .brand {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            padding-bottom: 20px;\n");
      out.write("            border-bottom: 1px solid #e5e7eb;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .brand i {\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("            color: var(--primary);\n");
      out.write("            margin-right: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .brand span {\n");
      out.write("            font-size: 1.25rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: var(--dark);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .side-menu {\n");
      out.write("            margin-top: 30px;\n");
      out.write("            list-style: none;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .side-menu li {\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .side-menu a {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 10px;\n");
      out.write("            color: var(--dark);\n");
      out.write("            text-decoration: none;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .side-menu a:hover,\n");
      out.write("        .side-menu a.active {\n");
      out.write("            background: var(--primary);\n");
      out.write("            color: #fff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .side-menu a i {\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("            margin-right: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Content */\n");
      out.write("        .content {\n");
      out.write("            margin-left: 260px;\n");
      out.write("            padding: 30px;\n");
      out.write("            transition: all 0.4s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .content-header {\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .header-title h1 {\n");
      out.write("            font-size: 1.75rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: var(--dark);\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Cards */\n");
      out.write("        .cards {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));\n");
      out.write("            gap: 20px;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card {\n");
      out.write("            background: #fff;\n");
      out.write("            padding: 20px;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            box-shadow: 0 0 20px rgba(0,0,0,0.1);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-icon {\n");
      out.write("            width: 40px;\n");
      out.write("            height: 40px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-icon.courses {\n");
      out.write("            background: #e0e7ff;\n");
      out.write("            color: var(--primary);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-icon.students {\n");
      out.write("            background: #dcfce7;\n");
      out.write("            color: var(--success);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-icon.assignments {\n");
      out.write("            background: #fef3c7;\n");
      out.write("            color: var(--warning);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-icon.submissions {\n");
      out.write("            background: #fee2e2;\n");
      out.write("            color: var(--danger);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card h3 {\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: var(--dark);\n");
      out.write("            margin-bottom: 5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card p {\n");
      out.write("            color: #64748b;\n");
      out.write("            font-size: 0.875rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Tables */\n");
      out.write("        .table-card {\n");
      out.write("            background: #fff;\n");
      out.write("            padding: 20px;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            box-shadow: 0 0 20px rgba(0,0,0,0.1);\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .table-header {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .table-title {\n");
      out.write("            font-size: 1.25rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: var(--dark);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-button {\n");
      out.write("            padding: 8px 16px;\n");
      out.write("            background: var(--primary);\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-button:hover {\n");
      out.write("            background: var(--secondary);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        th, td {\n");
      out.write("            padding: 12px;\n");
      out.write("            text-align: left;\n");
      out.write("            border-bottom: 1px solid #e5e7eb;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        th {\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: var(--dark);\n");
      out.write("            background: var(--light);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        td {\n");
      out.write("            color: #64748b;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status {\n");
      out.write("            padding: 6px 12px;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            font-size: 0.875rem;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-active {\n");
      out.write("            background: #dcfce7;\n");
      out.write("            color: var(--success);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-pending {\n");
      out.write("            background: #fef3c7;\n");
      out.write("            color: var(--warning);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-graded {\n");
      out.write("            background: #e0e7ff;\n");
      out.write("            color: var(--primary);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-icons {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-icons i {\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            color: var(--dark);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-icons i:hover {\n");
      out.write("            color: var(--primary);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Responsive */\n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .sidebar {\n");
      out.write("                left: -260px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .content {\n");
      out.write("                margin-left: 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .sidebar.active {\n");
      out.write("                left: 0;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Sidebar -->\n");
      out.write("    <div class=\"sidebar\">\n");
      out.write("        <div class=\"brand\">\n");
      out.write("            <i class=\"bi bi-code-square\"></i>\n");
      out.write("            <span>E-Learning</span>\n");
      out.write("        </div>\n");
      out.write("        <ul class=\"side-menu\">\n");
      out.write("            <li><a href=\"index.jsp\"><i class=\"bi bi-house\"></i> Home</a></li>\n");
      out.write("            <li><a href=\"#\" class=\"active\"><i class=\"bi bi-grid\"></i> Dashboard</a></li>\n");
      out.write("            <li><a href=\"#\"><i class=\"bi bi-book\"></i> My Courses</a></li>\n");
      out.write("            <li><a href=\"#\"><i class=\"bi bi-file-text\"></i> Assignments</a></li>\n");
      out.write("            <li><a href=\"#\"><i class=\"bi bi-people\"></i> Students</a></li>\n");
      out.write("            <li><a href=\"#\"><i class=\"bi bi-graph-up\"></i> Grades</a></li>\n");
      out.write("            <li><a href=\"#\"><i class=\"bi bi-calendar\"></i> Schedule</a></li>\n");
      out.write("            <li><a href=\"#\"><i class=\"bi bi-person\"></i> Profile</a></li>\n");
      out.write("            <li><a href=\"#\"><i class=\"bi bi-box-arrow-right\"></i> Logout</a></li>\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Content -->\n");
      out.write("    <div class=\"content\">\n");
      out.write("        <!-- Header -->\n");
      out.write("        <div class=\"content-header\">\n");
      out.write("            <div class=\"header-title\">\n");
      out.write("                <h1>Instructor Dashboard</h1>\n");
      out.write("                <p>Welcome back, Professor!</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Cards -->\n");
      out.write("        <div class=\"cards\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <div class=\"card-icon courses\">\n");
      out.write("                    <i class=\"bi bi-book\"></i>\n");
      out.write("                </div>\n");
      out.write("                <h3>4</h3>\n");
      out.write("                <p>Active Courses</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <div class=\"card-icon students\">\n");
      out.write("                    <i class=\"bi bi-people\"></i>\n");
      out.write("                </div>\n");
      out.write("                <h3>120</h3>\n");
      out.write("                <p>Total Students</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <div class=\"card-icon assignments\">\n");
      out.write("                    <i class=\"bi bi-file-text\"></i>\n");
      out.write("                </div>\n");
      out.write("                <h3>8</h3>\n");
      out.write("                <p>Active Assignments</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <div class=\"card-icon submissions\">\n");
      out.write("                    <i class=\"bi bi-inbox\"></i>\n");
      out.write("                </div>\n");
      out.write("                <h3>25</h3>\n");
      out.write("                <p>Pending Reviews</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Course Table -->\n");
      out.write("        <div class=\"table-card\">\n");
      out.write("            <div class=\"table-header\">\n");
      out.write("                <h2 class=\"table-title\">My Courses</h2>\n");
      out.write("                <button class=\"action-button\">Add New Course</button>\n");
      out.write("            </div>\n");
      out.write("            <table>\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>Course Name</th>\n");
      out.write("                        <th>Students</th>\n");
      out.write("                        <th>Start Date</th>\n");
      out.write("                        <th>Status</th>\n");
      out.write("                        <th>Actions</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>Java Programming</td>\n");
      out.write("                        <td>45 Students</td>\n");
      out.write("                        <td>Jan 15, 2024</td>\n");
      out.write("                        <td><span class=\"status status-active\">Active</span></td>\n");
      out.write("                        <td class=\"action-icons\">\n");
      out.write("                            <i class=\"bi bi-pencil-square\"></i>\n");
      out.write("                            <i class=\"bi bi-eye\"></i>\n");
      out.write("                            <i class=\"bi bi-trash\"></i>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>Web Development</td>\n");
      out.write("                        <td>38 Students</td>\n");
      out.write("                        <td>Jan 10, 2024</td>\n");
      out.write("                        <td><span class=\"status status-active\">Active</span></td>\n");
      out.write("                        <td class=\"action-icons\">\n");
      out.write("                            <i class=\"bi bi-pencil-square\"></i>\n");
      out.write("                            <i class=\"bi bi-eye\"></i>\n");
      out.write("                            <i class=\"bi bi-trash\"></i>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>Database Management</td>\n");
      out.write("                        <td>37 Students</td>\n");
      out.write("                        <td>Jan 20, 2024</td>\n");
      out.write("                        <td><span class=\"status status-pending\">Upcoming</span></td>\n");
      out.write("                        <td class=\"action-icons\">\n");
      out.write("                            <i class=\"bi bi-pencil-square\"></i>\n");
      out.write("                            <i class=\"bi bi-eye\"></i>\n");
      out.write("                            <i class=\"bi bi-trash\"></i>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Assignments Table -->\n");
      out.write("        <div class=\"table-card\">\n");
      out.write("            <div class=\"table-header\">\n");
      out.write("                <h2 class=\"table-title\">Recent Assignments</h2>\n");
      out.write("                <button class=\"action-button\">Create Assignment</button>\n");
      out.write("            </div>\n");
      out.write("            <table>\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>Assignment</th>\n");
      out.write("                        <th>Course</th>\n");
      out.write("                        <th>Due Date</th>\n");
      out.write("                        <th>Submissions</th>\n");
      out.write("                        <th>Status</th>\n");
      out.write("                        <th>Actions</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>Final Project</td>\n");
      out.write("                        <td>Java Programming</td>\n");
      out.write("                        <td>Feb 15, 2024</td>\n");
      out.write("                        <td>32/45</td>\n");
      out.write("                        <td><span class=\"status status-active\">Active</span></td>\n");
      out.write("                        <td class=\"action-icons\">\n");
      out.write("                            <i class=\"bi bi-pencil-square\"></i>\n");
      out.write("                            <i class=\"bi bi-eye\"></i>\n");
      out.write("                            <i class=\"bi bi-trash\"></i>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>Database Design</td>\n");
      out.write("                        <td>Database Management</td>\n");
      out.write("                        <td>Feb 10, 2024</td>\n");
      out.write("                        <td>35/37</td>\n");
      out.write("                        <td><span class=\"status status-graded\">Graded</span></td>\n");
      out.write("                        <td class=\"action-icons\">\n");
      out.write("                            <i class=\"bi bi-pencil-square\"></i>\n");
      out.write("                            <i class=\"bi bi-eye\"></i>\n");
      out.write("                            <i class=\"bi bi-trash\"></i>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Scripts -->\n");
      out.write("    <script src=\"assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    <script src=\"assets/vendor/aos/aos.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        // Initialize AOS\n");
      out.write("        AOS.init();\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
